name: Example-Expansion
version: '${version}'
author: 4drian3d
main: io.github.miniplaceholders.expansion.vault.paper.PaperPlugin
api-version: '1.19'
folia-supported: true
dependencies:
  server:
    MiniPlaceholders:
      required: true
    Vault:
      required: true
